### ISSUE TITLE
新的linux输入法，支持一波

### ISSUE THREAD

**Issue by y010204025** [qingxiang-jia/ibus-cloud-pinyin#1]
首先感谢制作了这个输入法，不过我看您的介绍，是绕过了ibus这个框架，直接使用Dus实现，似乎把ibus改成别的，比如说linux或者别的什么，这样感觉更合理，个人愚见。

**Comment by qingxiang-jia** [comment]
你好，谢谢你的支持。我觉得也不算是绕过IBus：这个项目用的还是IBus，只是绕过了IBus自己提供的C API，而直接用Rust的DBus给IBus发消息。原因主要是希望能完全用Rust写。如果还有什么问题可以重开这个issue。
